---
# handlers file for roles/icinga2
- name: restart apache2
  service: name=apache2 state=restarted

- name: restart icinga2
  service:
    name: icinga2
    state: restarted

# # - name: restart apache2
# #   service: name=httpd state=restarted
# - name: restart apache
#     service:
#       name: httpd
#       state: restarted
#   # service:
#   #   name: apache2
#   #   state: restarted
